# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kat Fukui
email: katherinefukui@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kat Fukui is a curious Product Designer and geeky cat lady.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://katfukui.com" # the base hostname & protocol for your site
twitter_username: katfukui
github_username:  katmeister
dribbble_username: katfukui
instagram_username: katfukui

# http://jekyllrb.com/docs/permalinks/
permalink:   /work/:title/

# Build settings
markdown: kramdown
